### ISSUE TITLE
There is an alternative other than this translation

### ISSUE THREAD

**Issue by kuangdash** [emacs-china/emacs-lisp-style-guide#3]
see the link: 
http://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html#Tips

**Comment by xuchunyang** [comment]
That official material is already mentioned in emacs-lisp-style-guide. 

By the way, if you have any issue with the content of emacs-lisp-style-guide, please file an issue from bbatsov/emacs-lisp-style-guide, instead of emacs-china/emacs-lisp-style-guide.
